name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ASIAW3MEAS2OM4EBMLQ4}}
          AWS_SECRET_ACCESS_KEY: ${{aYTHvk6fbqONOAaWN2Dtgq0+4xdV0XxcGZWf/Vpq}}
